language: node_js
node_js:
    - "node"
before_script:
    - npm install -g istanbul
    - npm install -g codeclimate-test-reporter
after_script:
    - codeclimate-test-reporter < /home/travis/build/chrised/node-ed2k/test/coverage/lcov.info
